### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by achimismaili** [PowershellNinja/OVF.SharePoint#1]
Hello Raphael, 
this module sounds really interesting. 
Would it be possible to add a simple 'getting started' section to your readme file?
I imported the prerequisites and your module and I am trying to figure out, how I could start a test now ...
(I am running PowerShell version 4.0 and/or ISE (in 64 bit and as admin with farm admin rights) on windows server 2012 with SP 2013 Enterprise)

**Comment by PowershellNinja** [comment]
Hi Achim

Sure, that has been on my ToDo List all the time, just got pushed backwards and backwards.... ;)

I'll try to do it as soon as possible!

**Comment by PowershellNinja** [comment]
Hi Achim

I enhanced the readme to contain info on setup and and configuration. Apart from some grammar mistakes, it should now more or less completely guide you through the whole "Getting Started" process.

Please let me know what you think, if you find it useful and if anything is unclear please tell me too.

Thanks and happy testing!

**Comment by achimismaili** [comment]
Thanks a lot, Raphael! Very well done!
With this guidance, I was now able to start my journey to become a real Operation-Validator ... ;)

**Comment by PowershellNinja** [comment]
Hi Achim
Glad you like it! If you have any more questions or suggestions, please feel free to open another issue.

Happy validation ;-)
